spring:
  datasource:
    url: jdbc:h2:mem:testdb
  security:
    basic:
      enabled: false

  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      jdbc.lob.non_contextual_creation: true
