spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/take_away
    username: take_away
    password: take_away
  mvc.locale: ru_RU
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.lob.non_contextual_creation: true
  flyway.locations: classpath:db/migrations

server:
  port: 8080
  servlet.context-path: /rest/api

logging:
  level:
    root: INFO
    sql: WARN
    web: INFO