spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ta_restaurant
    hikari:
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
  servlet.context-path: /rest/api

logging:
  level:
    sql: WARN
    web: ERROR